#!/usr/bin/env php
<?php

if(strpos(basename(__FILE__), 'phar')){
    require_once 'phar://ocok.phar/vendor/autoload.php';
}
else{
    if (file_exists(__DIR__.'/vendor/autoload.php')) {
        require_once __DIR__.'/vendor/autoload.php';
    } elseif (file_exists(__DIR__.'/../../autoload.php')) {
        require_once __DIR__ . '/../../autoload.php';
    } else {
        require_once 'phar://ocok.phar/vendor/autoload.php';
    }
}

use BeyondIT\OCOK\PHPDocCommand;
use BeyondIT\OCOK\CliTaskCommand;
use BeyondIT\OCOK\InfoCommand;
use BeyondIT\OCOK\InstallCommand;
use BeyondIT\OCOK\BackupCommand;
use BeyondIT\OCOK\GeneratorCommand;
use BeyondIT\OCOK\Helpers\DummyConfig;
use Symfony\Component\Console\Application;

$config = new DummyConfig();

$application = new Application();

$application->setName("OpenCart OK Command Line Utilities");

$application->add(new PHPDocCommand);
$application->add(new CliTaskCommand);
$application->add(new InstallCommand);
$application->add(new BackupCommand);
$application->add(new GeneratorCommand);
$application->add(new InfoCommand);


$application->setDefaultCommand('info');
$application->run();